
\echo Use "CREATE EXTENSION extra_funcs" to load this file. \quit


CREATE OR REPLACE FUNCTION iif_c(BOOLEAN, DOUBLE PRECISION, DOUBLE PRECISION) RETURNS DOUBLE PRECISION
     AS 'MODULE_PATHNAME'
     LANGUAGE C IMMUTABLE STRICT;

